Replace deprecated `project` with projected type
Diggsey/actix-interop pull request #2
Opened 2020-09-28 22:19 UTC by jmagnuson

Ref: https://github.com/taiki-e/pin-project/blob/v0.4.21/CHANGELOG.md#0421---2020-06-13

---

Also open to migrating to `pin_project_lite` which is supposed to be lighter-weight, but as-is this was a pretty quick change.

Original error:
```
Compiling actix-interop v0.1.1 (/home/jon/src/oss/actix-interop)
error: use of deprecated item 'project': consider naming projected type by passing `project` argument to #[pin_project] attribute instead, see release note <https://github.com/taiki-e/pin-project/releases/tag/v0.4.21> for details
   --> src/local_handle.rs:54:7
    |
54  |     #[project]
    |       ^^^^^^^
    |
note: the lint level is defined here
   --> src/lib.rs:144:23
    |
144 | #![deny(missing_docs, warnings)]
    |                       ^^^^^^^^
    = note: `#[deny(deprecated)]` implied by `#[deny(warnings)]`
```

2020-09-28 23:41 UTC, Diggsey approved these changes

2020-09-28 23:42 UTC, Diggsey requested changes
Actually, I think you'll also need to bump the required version of `pin-project`.

2020-09-29 00:11 UTC, jmagnuson commented
Good catch-- done.

2020-09-29 00:39 UTC, Diggsey commented
Thanks! 👍

2020-09-29 00:39 UTC, merged